---
roles:
  - name: chriswayg.msmtp-mailer
    src: https://github.com/chriswayg/ansible-msmtp-mailer
    version: v0.6.1

collections:
  - name: https://github.com/ansible-collections/community.docker
    type: git
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.crypto
    type: git
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
