---
- name: Install iptables-persistent
  ansible.builtin.package:
    name: iptables-persistent

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Allow the defined ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item.proto }}"
    ctstate: NEW
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  with_items:
    - "{{ firewall_ports }}"

- name: Save current state of the firewall in system file
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4
