---
- name: Install firewalld and dependencies
  ansible.builtin.package:
    name:
      - firewalld
      - python3-firewall
    state: present

- name: Configure the firewall with system python3.6 if on CentOS 8
  when: ansible_distribution_major_version | int == 8
  ansible.builtin.set_fact:
    ansible_python_interpreter: "/usr/bin/python3.6"

- name: Configure the firewall with system python3.9 if on CentOS 9
  when: ansible_distribution_major_version | int == 9
  ansible.builtin.set_fact:
    ansible_python_interpreter: "/usr/bin/python3"

- name: Configure firewalld
  block:
    - name: Allow the defined ports
      ansible.posix.firewalld:
        permanent: true
        port: "{{ item.port }}/{{ item.proto }}"
        state: enabled
      with_items:
        - "{{ firewall_ports }}"
  rescue:
    - name: Grant SSH access to prevent lockout
      ansible.posix.firewalld:
        permanent: true
        port: "{{ ssh_port }}/tcp"

- name: Put the venv python interpreter back in place
  ansible.builtin.set_fact:
    ansible_python_interpreter: "/{{ lookup('env', 'HOME') }}/ansible-easy-vpn/.venv/bin/python3"

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
